CAR_CATALOG = {
    'Abarth': ['500','500C','595','595C','695','695C','Grande Punto','Punto Evo'],
    'Alfa Romeo': ['33','75','145','146','147','155','156','159','164','166','4C','4C Spider','Brera','Giulia','Giulietta','GT','GTV','MiTo','Spider','Stelvio','Tonale'],
    'Alpine': ['A110','A290'],
    'Aston Martin': ['DB7','DB9','DB11','DB12','DBS','Rapide','V8 Vantage','V12 Vantage','Vanquish','DBX'],
    'Audi': ['80','90','100','A1','A2','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4 e-tron','Q5','Q6 e-tron','Q7','Q8','R8','TT','e-tron GT','e-tron'],
    'Bentley': ['Arnage','Bentayga','Continental GT','Continental GTC','Flying Spur','Mulsanne'],
    'BMW': ['Serie 1','Serie 2','Serie 3','Serie 4','Serie 5','Serie 6','Serie 7','Serie 8','X1','X2','X3','X4','X5','X6','X7','Z3','Z4','i3','i4','i5','i7','i8','iX','iX1','iX2','iX3'],
    'BYD': ['Atto 2','Atto 3','Dolphin','Dolphin Surf','Han','Seal','Seal U','Sealion 7','Tang'],
    'Cadillac': ['ATS','BLS','CTS','Escalade','SRX','XT4','XT5'],
    'Chevrolet': ['Aveo','Camaro','Captiva','Corvette','Cruze','Epica','Kalos','Lacetti','Matiz','Orlando','Spark','Trax'],
    'Chrysler': ['300C','Grand Voyager','PT Cruiser','Sebring','Voyager'],
    'Citroen': ['AX','BX','C1','C2','C3','C3 Aircross','C4','C4 Cactus','C4 Picasso','C4 SpaceTourer','C5','C5 Aircross','C6','C8','DS3','DS4','DS5','Saxo','Berlingo','Jumper','Jumpy','Nemo','Xantia','Xsara','Xsara Picasso'],
    'Cupra': ['Ateca','Born','Formentor','Leon','Tavascan','Terramar'],
    'Dacia': ['Bigster','Doker','Duster','Jogger','Lodgy','Logan','Sandero','Spring'],
    'Daewoo': ['Kalos','Lanos','Leganza','Matiz','Nubira'],
    'Daihatsu': ['Copen','Cuore','Materia','Sirion','Terios','YRV'],
    'Dodge': ['Caliber','Challenger','Charger','Journey','Nitro','RAM'],
    'DR': ['DR1','DR2','DR3','DR4','DR5','DR6','DR7','DR Evo 5','DR Evo 7'],
    'DS Automobiles': ['DS 3','DS 3 Crossback','DS 4','DS 5','DS 7','DS 9'],
    'EVO': ['EVO 3','EVO 4','EVO 5','EVO 6','EVO 7'],
    'Ferrari': ['208','308','328','348','360','430','458','488','550','575M','599','612','812','California','F8 Tributo','F12berlinetta','GTC4Lusso','Portofino','Purosangue','Roma','SF90 Stradale'],
    'Fiat': ['124 Spider','126','127','128','131','500','500C','500e','500L','500X','600','600e','Barchetta','Bravo','Brava','Cinquecento','Croma','Doblò','Ducato','Fiorino','Freemont','Grande Punto','Idea','Marea','Multipla','Palio','Panda','Punto','Punto Evo','Qubo','Scudo','Sedici','Seicento','Stilo','Talento','Tipo','Uno','Ulysse'],
    'Ford': ['B-Max','C-Max','Capri','EcoSport','Edge','Escort','Explorer','Fiesta','Focus','Fusion','Galaxy','Ka','Ka+','Kuga','Mondeo','Mustang','Mustang Mach-E','Puma','Ranger','S-Max','Tourneo Connect','Tourneo Courier','Tourneo Custom','Transit','Transit Connect','Transit Courier','Transit Custom'],
    'Honda': ['Accord','Civic','CR-V','CR-Z','e','FR-V','HR-V','Insight','Jazz','Legend','NSX','S2000','ZR-V'],
    'Hyundai': ['Atos','Bayon','Coupe','Getz','Grandeur','i10','i20','i30','i40','IONIQ','IONIQ 5','IONIQ 6','ix20','ix35','Kona','Matrix','Santa Fe','Sonata','Terracan','Trajet','Tucson','Veloster'],
    'Infiniti': ['EX','FX','G','M','Q30','Q50','Q60','Q70','QX30','QX50','QX70'],
    'Isuzu': ['D-Max','Trooper'],
    'Iveco': ['Daily'],
    'Jaguar': ['E-Pace','F-Pace','F-Type','I-Pace','S-Type','X-Type','XE','XF','XJ','XK'],
    'Jeep': ['Avenger','Cherokee','Commander','Compass','Grand Cherokee','Patriot','Renegade','Wrangler'],
    'Kia': ['Carens','Carnival','Ceed','e-Niro','EV3','EV6','EV9','Niro','Optima','Picanto','ProCeed','Rio','Sorento','Soul','Sportage','Stinger','Stonic','Venga','XCeed'],
    'Lamborghini': ['Aventador','Countach','Diablo','Gallardo','Huracán','Murciélago','Revuelto','Urus'],
    'Lancia': ['Delta','Dedra','Flavia','Kappa','Lybra','Musa','Phedra','Prisma','Thema','Thesis','Y','Y10','Ypsilon'],
    'Land Rover': ['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar'],
    'Lexus': ['CT','ES','GS','IS','LBX','LC','LS','NX','RC','RX','RZ','UX'],
    'Lotus': ['Elise','Emira','Esprit','Evora','Exige','Eletre'],
    'Maserati': ['3200 GT','Ghibli','GranCabrio','GranTurismo','Grecale','Levante','MC20','Quattroporte'],
    'Mazda': ['2','3','5','6','CX-3','CX-30','CX-5','CX-60','CX-80','CX-7','MX-30','MX-5','RX-8'],
    'Mercedes-Benz': ['Classe A','Classe B','Classe C','Classe CL','Classe CLA','Classe CLC','Classe CLK','Classe CLS','Classe E','Classe G','Classe GL','Classe GLA','Classe GLB','Classe GLC','Classe GLE','Classe GLK','Classe GLS','Classe M','Classe R','Classe S','Classe SL','Classe SLK','Classe SLC','Citan','EQA','EQB','EQC','EQE','EQS','EQV','Sprinter','Viano','Vito','Classe V'],
    'MG': ['MG3','MG4','MG5','HS','EHS','Marvel R','ZS','Cyberster'],
    'MINI': ['Mini','Cabrio','Clubman','Countryman','Coupe','Paceman','Roadster','Aceman'],
    'Mitsubishi': ['ASX','Carisma','Colt','Eclipse Cross','Grandis','L200','Lancer','Outlander','Pajero','Space Star'],
    'Nissan': ['200SX','350Z','370Z','Almera','Ariya','Cube','Juke','Leaf','Micra','Murano','Navara','Note','Pathfinder','Patrol','Primera','Pulsar','Qashqai','Terrano','X-Trail'],
    'Opel': ['Adam','Agila','Ampera','Antara','Astra','Calibra','Combo','Corsa','Crossland','Frontera','Grandland','Insignia','Karl','Meriva','Mokka','Omega','Signum','Tigra','Vectra','Vivaro','Zafira'],
    'Peugeot': ['1007','106','107','108','2008','205','206','207','208','3008','306','307','308','4007','4008','405','406','407','408','5008','508','607','807','Bipper','Boxer','Expert','Partner','RCZ','Rifter'],
    'Polestar': ['1','2','3','4'],
    'Porsche': ['718 Boxster','718 Cayman','911','Boxster','Cayenne','Cayman','Macan','Panamera','Taycan'],
    'Renault': ['5 E-Tech','Arkana','Austral','Captur','Clio','Espace','Fluence','Kadjar','Kangoo','Koleos','Laguna','Master','Megane','Modus','Rafale','Scenic','Talisman','Trafic','Twingo','Vel Satis','Zoe'],
    'Saab': ['9-3','9-5','900','9000'],
    'SEAT': ['Alhambra','Altea','Arona','Arosa','Ateca','Cordoba','Exeo','Ibiza','Leon','Mii','Tarraco','Toledo'],
    'Skoda': ['Citigo','Elroq','Enyaq','Fabia','Kamiq','Karoq','Kodiaq','Octavia','Rapid','Roomster','Scala','Superb','Yeti'],
    'Smart': ['ForFour','ForTwo','#1','#3','#5'],
    'SsangYong / KGM': ['Actyon','Korando','Kyron','Musso','Rexton','Rodius','Tivoli','Torres'],
    'Subaru': ['BRZ','Forester','Impreza','Legacy','Levorg','Outback','Solterra','Trezia','Tribeca','XV'],
    'Suzuki': ['Across','Alto','Baleno','Grand Vitara','Ignis','Jimny','Kizashi','Liana','S-Cross','Splash','Swift','SX4','Vitara','Wagon R+'],
    'Tesla': ['Model 3','Model S','Model X','Model Y','Roadster'],
    'Toyota': ['Auris','Avensis','Aygo','Aygo X','bZ4X','C-HR','Camry','Celica','Corolla','Corolla Cross','GT86','Highlander','Hilux','Land Cruiser','Mirai','Prius','Proace','RAV4','Supra','Urban Cruiser','Verso','Yaris','Yaris Cross'],
    'Volkswagen': ['Amarok','Arteon','Beetle','Bora','Caddy','Caravelle','Crafter','Eos','Fox','Golf','ID.3','ID.4','ID.5','ID.7','ID.Buzz','Jetta','Lupo','Multivan','New Beetle','Passat','Phaeton','Polo','Scirocco','Sharan','T-Cross','T-Roc','Taigo','Tiguan','Touareg','Touran','Transporter','Up!'],
    'Volvo': ['C30','C40','C70','EX30','EX40','EX90','S40','S60','S80','S90','V40','V50','V60','V70','V90','XC40','XC60','XC70','XC90'],
}
