CAR_CATALOG = {
    'Abarth': ['124 Spider','500','500C','595','695','Punto Evo'],
    'Alfa Romeo': ['4C','33','75','145','146','147','156','159','166','Brera','Giulia','Giulietta','GT','MiTo','Spider','Stelvio','Tonale','Junior'],
    'Audi': ['A1','A2','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4 e-tron','Q5','Q6 e-tron','Q7','Q8','R8','TT','e-tron','e-tron GT'],
    'BMW': ['Serie 1','Serie 2','Serie 3','Serie 4','Serie 5','Serie 6','Serie 7','Serie 8','X1','X2','X3','X4','X5','X6','X7','Z3','Z4','i3','i4','i5','i7','iX','iX1','iX2','iX3'],
    'Citroen': ['AMI','Berlingo','C1','C2','C3','C3 Aircross','C4','C4 Cactus','C4 Picasso','C4 X','C5','C5 Aircross','C5 X','C6','C8','DS3','Jumper','Jumpy','Saxo','Xsara','Xsara Picasso'],
    'Cupra': ['Ateca','Born','Formentor','Leon','Tavascan','Terramar'],
    'Dacia': ['Bigster','Duster','Jogger','Lodgy','Logan','Sandero','Spring'],
    'DS': ['DS 3','DS 4','DS 5','DS 7','DS 9'],
    'Fiat': ['124 Spider','500','500C','500e','500L','500X','600','600e','Bravo','Croma','Doblò','Ducato','Fiorino','Freemont','Grande Panda','Grande Punto','Idea','Multipla','Panda','Punto','Punto Evo','Qubo','Scudo','Sedici','Stilo','Talento','Tipo','Ulysse'],
    'Ford': ['B-Max','C-Max','EcoSport','Edge','Explorer','Fiesta','Focus','Fusion','Galaxy','Ka','Kuga','Mondeo','Mustang','Mustang Mach-E','Puma','Ranger','S-Max','Tourneo','Transit'],
    'Honda': ['Accord','Civic','CR-V','e','e:Ny1','FR-V','HR-V','Jazz','NSX','ZR-V'],
    'Hyundai': ['Bayon','i10','i20','i30','i40','IONIQ','IONIQ 5','IONIQ 6','ix20','ix35','Kona','Santa Fe','Tucson'],
    'Jaguar': ['E-Pace','F-Pace','F-Type','I-Pace','S-Type','XE','XF','XJ','X-Type'],
    'Jeep': ['Avenger','Cherokee','Commander','Compass','Grand Cherokee','Patriot','Renegade','Wrangler'],
    'Kia': ['Carens','Ceed','EV3','EV6','EV9','Niro','Optima','Picanto','ProCeed','Rio','Sorento','Soul','Sportage','Stinger','Stonic','Venga','XCeed'],
    'Lancia': ['Delta','Kappa','Lybra','Musa','Phedra','Thema','Thesis','Y','Ypsilon'],
    'Land Rover': ['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar'],
    'Lexus': ['CT','ES','GS','IS','LBX','LC','LS','NX','RC','RX','RZ','UX'],
    'Mazda': ['2','3','5','6','CX-3','CX-30','CX-5','CX-60','CX-80','MX-30','MX-5','RX-8'],
    'Mercedes-Benz': ['Classe A','Classe B','Classe C','Classe E','Classe G','Classe S','CLA','CLC','CLK','CLS','EQA','EQB','EQC','EQE','EQS','GLA','GLB','GLC','GLE','GLK','GLS','SL','SLK','Vito','Classe V'],
    'Mini': ['Cabrio','Clubman','Cooper','Countryman','One','Paceman'],
    'Mitsubishi': ['ASX','Colt','Eclipse Cross','L200','Lancer','Outlander','Pajero','Space Star'],
    'Nissan': ['350Z','370Z','Ariya','Juke','Leaf','Micra','Murano','Navara','Note','Pathfinder','Primera','Pulsar','Qashqai','Terrano','X-Trail'],
    'Opel': ['Adam','Agila','Antara','Astra','Corsa','Crossland','Frontera','Grandland','Insignia','Karl','Meriva','Mokka','Omega','Signum','Tigra','Vectra','Vivaro','Zafira'],
    'Peugeot': ['1007','106','107','108','2008','206','207','208','3008','306','307','308','4007','407','5008','508','607','807','Bipper','Expert','Partner','RCZ','Rifter'],
    'Porsche': ['718 Boxster','718 Cayman','911','Cayenne','Macan','Panamera','Taycan'],
    'Renault': ['Arkana','Austral','Captur','Clio','Espace','Fluence','Kadjar','Kangoo','Laguna','Master','Megane','Modus','Rafale','Scenic','Symbioz','Talisman','Trafic','Twingo','Zoe'],
    'Seat': ['Alhambra','Altea','Arona','Arosa','Ateca','Cordoba','Exeo','Ibiza','Leon','Mii','Tarraco','Toledo'],
    'Skoda': ['Citigo','Elroq','Enyaq','Fabia','Kamiq','Karoq','Kodiaq','Octavia','Rapid','Roomster','Scala','Superb','Yeti'],
    'Smart': ['ForFour','ForTwo','#1','#3','#5'],
    'Subaru': ['BRZ','Forester','Impreza','Legacy','Levorg','Outback','Solterra','XV'],
    'Suzuki': ['Across','Alto','Baleno','Ignis','Jimny','S-Cross','Splash','Swift','SX4','Vitara'],
    'Tesla': ['Model 3','Model S','Model X','Model Y'],
    'Toyota': ['Auris','Aygo','Aygo X','bZ4X','C-HR','Camry','Celica','Corolla','GR86','Highlander','Hilux','Land Cruiser','Prius','Proace','RAV4','Supra','Verso','Yaris','Yaris Cross'],
    'Volkswagen': ['Arteon','Beetle','Bora','Caddy','Caravelle','Crafter','Eos','Fox','Golf','ID.3','ID.4','ID.5','ID.7','ID.Buzz','Jetta','Lupo','Multivan','Passat','Phaeton','Polo','Scirocco','Sharan','T-Cross','T-Roc','Taigo','Tiguan','Touareg','Touran','Transporter','Up!'],
    'Volvo': ['C30','C40','C70','EX30','EX40','EX90','S40','S60','S80','S90','V40','V50','V60','V70','V90','XC40','XC60','XC70','XC90'],
}
